
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example;

/** CUP generated interface containing symbol constants. */
public interface TiposDeToken {
  /* terminals */
  public static final int INTERROGATION = 43;
  public static final int PALAVRA_RESERVADA_ELSE = 11;
  public static final int OPERADOR_EQUAL = 24;
  public static final int PALAVRA_RESERVADA_DO = 12;
  public static final int PALAVRA_RESERVADA_READ = 16;
  public static final int PALAVRA_RESERVADA_THEN = 10;
  public static final int OPERADOR_MULT = 33;
  public static final int IDENTIFICADOR = 3;
  public static final int SEMICOLON = 22;
  public static final int OPERADOR_RIGHT_SHIFT = 38;
  public static final int OPERADOR_GREATEQUAL = 26;
  public static final int OPERADOR_UNSIGNED_LEFT_SHIFT = 40;
  public static final int COMMA = 42;
  public static final int PALAVRA_RESERVADA_FOR = 14;
  public static final int RIGHT_PARENTHESIS = 19;
  public static final int OPERADOR_LESS = 27;
  public static final int PALAVRA_RESERVADA_NOT = 41;
  public static final int PALAVRA_RESERVADA_AND = 36;
  public static final int PALAVRA_RESERVADA_INTEGER = 7;
  public static final int PALAVRA_RESERVADA_WRITE = 17;
  public static final int OPERADOR_ASSIGN = 21;
  public static final int PALAVRA_RESERVADA_OR = 32;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PALAVRA_RESERVADA_IF = 9;
  public static final int CONSTANT = 44;
  public static final int PALAVRA_RESERVADA_BEGIN = 5;
  public static final int OPERADOR_LESSEQUAL = 28;
  public static final int COLON = 23;
  public static final int LITERAL = 20;
  public static final int OPERADOR_UNSIGNED_RIGHT_SHIFT = 39;
  public static final int PALAVRA_RESERVADA_MOD = 35;
  public static final int OPERADOR_GREAT = 25;
  public static final int OPERADOR_DIFFERENT = 29;
  public static final int OPERADOR_LEFT_SHIFT = 37;
  public static final int PALAVRA_RESERVADA_DECIMAL = 8;
  public static final int FLOAT_CONSTANT = 45;
  public static final int PALAVRA_RESERVADA_PROGRAM = 2;
  public static final int OPERADOR_MINUS = 31;
  public static final int OPERADOR_PART = 34;
  public static final int PALAVRA_RESERVADA_TO = 15;
  public static final int PALAVRA_RESERVADA_DECLARE = 4;
  public static final int OPERADOR_ADD = 30;
  public static final int PALAVRA_RESERVADA_WHILE = 13;
  public static final int LEFT_PARENTHESIS = 18;
  public static final int PALAVRA_RESERVADA_END = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PALAVRA_RESERVADA_PROGRAM",
  "IDENTIFICADOR",
  "PALAVRA_RESERVADA_DECLARE",
  "PALAVRA_RESERVADA_BEGIN",
  "PALAVRA_RESERVADA_END",
  "PALAVRA_RESERVADA_INTEGER",
  "PALAVRA_RESERVADA_DECIMAL",
  "PALAVRA_RESERVADA_IF",
  "PALAVRA_RESERVADA_THEN",
  "PALAVRA_RESERVADA_ELSE",
  "PALAVRA_RESERVADA_DO",
  "PALAVRA_RESERVADA_WHILE",
  "PALAVRA_RESERVADA_FOR",
  "PALAVRA_RESERVADA_TO",
  "PALAVRA_RESERVADA_READ",
  "PALAVRA_RESERVADA_WRITE",
  "LEFT_PARENTHESIS",
  "RIGHT_PARENTHESIS",
  "LITERAL",
  "OPERADOR_ASSIGN",
  "SEMICOLON",
  "COLON",
  "OPERADOR_EQUAL",
  "OPERADOR_GREAT",
  "OPERADOR_GREATEQUAL",
  "OPERADOR_LESS",
  "OPERADOR_LESSEQUAL",
  "OPERADOR_DIFFERENT",
  "OPERADOR_ADD",
  "OPERADOR_MINUS",
  "PALAVRA_RESERVADA_OR",
  "OPERADOR_MULT",
  "OPERADOR_PART",
  "PALAVRA_RESERVADA_MOD",
  "PALAVRA_RESERVADA_AND",
  "OPERADOR_LEFT_SHIFT",
  "OPERADOR_RIGHT_SHIFT",
  "OPERADOR_UNSIGNED_RIGHT_SHIFT",
  "OPERADOR_UNSIGNED_LEFT_SHIFT",
  "PALAVRA_RESERVADA_NOT",
  "COMMA",
  "INTERROGATION",
  "CONSTANT",
  "FLOAT_CONSTANT"
  };
}

